TODO
= Welcome to Red Hat Workshop - GitOps & Blue/Green & Promotion between environments
:page-layout: home
:!sectids:

[.text-center.strong]
== Introduction

_Red Hat Workshop GitOps & Blue/Green & Promotion between environments_ is a repository which includes a tutorial with a set of practices for the purpose of practicing with Kubernetes Native GitOps model, Blue/Green deployment and promotion between environments.

The general idea behind this workshop is to get an initial understanding of the following points:

- Deploy microservice-based applications in Kubernetes using ArgoCD and Helm
- Operate applications in Kubernetes using ArgoCD in a GitOps model
- Blue/Green deployment for Cloud Native applications
- Promotion between environments in a GitOps model.

[.text-center.strong]
== Getting Started

First of all, it is required to review your local machine prerequisites and laboratory environment access in order to be able to start working on this tutorial.

Please follow xref:01-setup.adoc[Environment Setup] for more information.

[.text-center.strong]
== Tutorial Steps

TODO or delete