apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configuration
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops/cluster-config
    repoURL: 'https://github.com/davidseve/cloud-native-deployment-strategies.git'
    targetRevision: environments
    helm:
      parameters:
        - name: "pipeline.enabled"
          value: 'false'
        - name: "github.enabled"
          value: 'false'
        - name: "bluegreen.enabled"
          value: 'false'  
        - name: "users[0]"
          value: user1
        - name: "users[1]"
          value: user2
        - name: "namespaces[0]"
          value: stage
        - name: "namespaces[1]"
          value: prod
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false