apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-configuration
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - environment: stage
      - environment: prod
  template:
    metadata:
      name: '{{environment}}-cluster-configuration'
      namespace: openshift-gitops
    spec:
      destination:
        name: ''
        namespace: openshift-gitops
        server: 'https://kubernetes.default.svc'
      source:
        path: gitops/cluster-config
        repoURL: 'https://github.com/davidseve/cloud-native-deployment-strategies.git'
        targetRevision: environments
        helm:
          parameters:
            - name: "namespace"
              value: '{{environment}}'
            - name: "pipeline.enabled"
              value: 'false'
            - name: "github.enabled"
              value: 'false'
            - name: "bluegreen.enabled"
              value: 'false'  
            - name: "monitoring.enabled"
              value: 'false'    
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: false 